# Generated by Django 3.1.4 on 2020-12-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='replicationauk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auk', models.BigIntegerField()),
                ('id_mt', models.BigIntegerField()),
                ('essence', models.CharField(max_length=50)),
                ('dt', models.DateTimeField()),
                ('comment', models.CharField(max_length=150)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
