# Generated by Django 3.1.4 on 2020-12-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='replicationauk',
            table='replicationauk',
        ),
    ]
