# Generated by Django 3.1.4 on 2021-01-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mt_client', '0002_replicationauk21'),
    ]

    operations = [
        migrations.DeleteModel(
            name='replicationauk21',
        ),
    ]
