# Generated by Django 3.1.4 on 2020-12-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastrunned', models.DateTimeField(verbose_name='lastrunned')),
                ('taskname', models.CharField(max_length=50, verbose_name='taskname')),
            ],
            options={
                'verbose_name': 'запуск',
                'verbose_name_plural': 'запуски',
            },
        ),
    ]
