# Generated by Django 3.1.4 on 2021-04-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initcmds', '0002_taskmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='fail',
            field=models.TextField(blank=True, null=True, verbose_name='fail'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('c', 'created'), ('p', 'progress'), ('s', 'success'), ('f', 'failed')], default='c', max_length=1),
        ),
    ]
