# Generated by Django 3.1.4 on 2020-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auk_id', models.IntegerField(blank=True, null=True)),
                ('mt_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'контейнер',
                'verbose_name_plural': 'контейнеры',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auk_id', models.IntegerField(blank=True, null=True)),
                ('mt_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(blank=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'платформа',
                'verbose_name_plural': 'платформы',
            },
        ),
    ]
