# Generated by Django 3.1.4 on 2021-01-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auk_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
