name: deploy to stage

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: stage
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: cp /projects/_config/mtauksync/.env ./.env
      - name: Modifying docker-compose
        run: cp /projects/_config/mtauksync/docker-compose.yml ./docker-compose.yml
      - name: Create volumes
        run: make volumes
      - name: Make up
        run: make up
